# Install
- name: Install Jenkins and needed software for Jenkins
  yum: state=present name={{ item }}
  with_items:
  - jenkins
  - git
  - rpm-build
  - ansible

- name: Start Jenkins
  service: name=jenkins state=started enabled=yes
