# Jobs
- name: Create Jenkins Jobs folder
  file: path={{ jenkins_home }}/jobs/{{ item }}/ mode=0775 owner=jenkins group=jenkins state="directory" recurse=yes
  with_items:
  - "{{ _jenkins_jbs }}"
- name: Config Jenkins Jobs
  template: src=jenkins/jobs/{{ item }}/config.xml.j2 dest={{ jenkins_home }}/jobs/{{ item }}/config.xml
  with_items:
  - "{{ _jenkins_jbs }}"